version: "3.9"

services:
  app:
    build:
        dockerfile: Dockerfile
    container_name: xgame-product-page-api
    platform: linux/amd64
    env_file:
      - .env
    ports:
      - 3005:3005

  copy-product-page-env:
    build:
        dockerfile: Dockerfile
    container_name: copy-product-page-env
    platform: linux/amd64
    volumes:
      - /var/oress/oress-xgame-product-page-api/.env:/temp/.env
    command: sh -c "cp /temp/.env /app/.env && exit"