name: production_deployment

on:
  push:
    tags:
      - v**-production

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build docker image
        run: docker build -t ${{ secrets.DOCKER_HUB_NAMESPACE }}/xgame-product-page-api:latest .

      - name: Push image to DockerHub
        run: |
          docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
          docker push ${{ secrets.DOCKER_HUB_NAMESPACE }}/xgame-product-page-api:latest
